### ISSUE TITLE
Update docs for static assets to describe how to add static assets through .ts file

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#301] opened 2018-08-16 15:29 UTC
Upate https://developer.blackbaud.com/skyux/learn/get-started/advanced/include-static-assets to include a section describing how to reference static assets in component.ts files. This came up in a Slack thread: https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1534276123000100.

**Comment by Blackbaud-BobbyEarl** [comment] 2019-05-08 21:41
Duplicate of #302.  Also fixed via https://github.com/blackbaud/skyux2-docs/pull/65

**Closed by Blackbaud-BobbyEarl** 2019-05-08 21:41 UTC
Labels: From: Consumer, Priority: Medium
